version: "3.9"
services:
  mongo:
    image: arm64v8/mongo
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: test.db
  app:
    build: .
    environment:
      DB_HOST: mongo
    depends_on:
      - mongo
